# definitions.py

import os
from pathlib import Path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv

    # Load .env from the script's directory
    env_path = Path(__file__).parent / ".env"
    load_dotenv(dotenv_path=env_path)
except ImportError:
    # dotenv not installed, rely on system environment variables
    pass


# HTTP headers for web scraping
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Cookie": os.getenv("SUBSTACK_COOKIE", ""),  # Load from environment variable
}

# Target URL - dynamically generated from SUBSTACK_USER
SUBSTACK_USER = os.getenv("SUBSTACK_USER", "")
if SUBSTACK_USER:
    # Ensure username starts with @
    if not SUBSTACK_USER.startswith("@"):
        SUBSTACK_USER = f"@{SUBSTACK_USER}"
    SUBSTACK_URL = f"https://substack.com/{SUBSTACK_USER}/reads"
else:
    # Fallback if SUBSTACK_USER not set
    SUBSTACK_URL = ""

# Keyword categories for auto-labeling
KEYWORD_CATEGORIES = {
    # Technology & Software
    "tech": [
        "technology",
        "tech",
        "software",
        "hardware",
        "coding",
        "programming",
        "developer",
        "engineering",
        "devops",
        "cybersecurity",
        "web development",
        "mobile app",
        "open source",
        "tech news",
        "silicon valley",
        "innovation",
        "digital",
        "internet",
        "cloud",
        "data",
        "platform",
        "api",
        "code",
        "tech industry",
        "tech company",
        "tech companies",
        "tech career",
        "tech worker",
        "tech culture",
        "product management",
        "product manager",
        "tech leadership",
        "engineering team",
        "software engineer",
        "tech talent",
        "tech manager",
        "engineering manager",
        "software manager",
        "vp of engineering",
        "cto",
        "chief technology officer",
    ],
    "ai": [
        "ai",
        "artificial intelligence",
        "machine learning",
        "ml",
        "deep learning",
        "neural network",
        "llm",
        "gpt",
        "chatbot",
        "nlp",
        "computer vision",
        "generative ai",
        "chatgpt",
        "openai",
        "anthropic",
        "claude",
        "gemini",
        "ai model",
        "training",
        "inference",
    ],
    "crypto": [
        "crypto",
        "cryptocurrency",
        "bitcoin",
        "ethereum",
        "blockchain",
        "web3",
        "defi",
        "nft",
        "smart contract",
        "decentralized",
        "solana",
        "token",
        "wallet",
        "mining",
        "exchange",
        "coinbase",
    ],
    "startups": [
        "startup",
        "startups",
        "founder",
        "venture capital",
        "vc",
        "saas",
        "entrepreneur",
        "fundraising",
        "product market fit",
        "mvp",
        "growth hacking",
        "y combinator",
        "seed round",
        "series a",
        "unicorn",
        "exit",
        "acquisition",
        "ipo",
    ],

    # Business & Finance
    "business": [
        "business",
        "commerce",
        "industry",
        "corporate",
        "management",
        "leadership",
        "strategy",
        "operations",
        "consulting",
        "ceo",
        "executive",
        "enterprise",
        "b2b",
        "b2c",
        "revenue",
        "profit",
        "business strategy",
        "business operations",
    ],
    "finance": [
        "finance",
        "investing",
        "stocks",
        "trading",
        "markets",
        "economy",
        "economics",
        "money",
        "wealth",
        "personal finance",
        "portfolio",
        "asset",
        "wall street",
        "financial",
        "investor",
        "fund",
        "hedge fund",
        "dividends",
        "bonds",
        "commodities",
        "real estate",
        "roi",
    ],
    "marketing": [
        "marketing",
        "growth",
        "branding",
        "advertising",
        "seo",
        "content marketing",
        "social media",
        "analytics",
        "conversion",
        "customer acquisition",
    ],

    # News & Politics
    "news": [
        "news",
        "journalism",
        "reporter",
        "correspondent",
        "breaking news",
        "current events",
        "headlines",
        "newsroom",
        "investigative",
        "reporting",
        "news briefing",
        "daily news",
        "press",
        "journalist",
        "media coverage",
        "news coverage",
        "news dispatch",
        "newsworthy",
        "briefing",
        "daily briefing",
    ],
    "politics": [
        "politics",
        "political",
        "policy",
        "government",
        "congress",
        "senate",
        "legislation",
        "election",
        "democracy",
        "governance",
        "public policy",
        "activist",
        "activism",
        "progressive",
        "conservative",
        "liberal",
        "rights",
        "civil rights",
        "human rights",
        "equality",
        "justice",
        "protest",
        "resistance",
        "reform",
        "congressman",
        "congresswoman",
        "representative",
        "senator",
        "political news",
        "political analysis",
        "capitol",
        "white house",
        "administration",
        "campaign",
    ],
    "world": [
        "international",
        "global",
        "geopolitics",
        "foreign policy",
        "diplomacy",
        "world affairs",
        "conflict",
        "war",
        "peace",
        "world news",
        "international news",
        "global news",
        "world briefing",
        "international relations",
        "foreign affairs",
        "united nations",
        "un",
        "nato",
        "summit",
        "treaty",
    ],

    # Creative & Culture
    "writing": [
        "writing",
        "storytelling",
        "creative writing",
        "fiction",
        "poetry",
        "prose",
        "essays",
        "memoir",
        "nonfiction",
        "narrative",
        "literary",
        "literary fiction",
        "short stories",
        "novelist",
        "columnist",
        "essayist",
    ],
    "culture": [
        "culture",
        "cultural",
        "society",
        "trends",
        "pop culture",
        "zeitgeist",
        "social commentary",
        "cultural criticism",
        "lifestyle",
        "community",
        "contemporary culture",
    ],
    "intersectionality": [
        "intersectionality",
        "intersectional",
        "identity",
        "marginalized",
        "minority",
        "bipoc",
        "black",
        "african american",
        "asian american",
        "latinx",
        "latine",
        "latina",
        "latino",
        "indigenous",
        "native american",
        "people of color",
        "queer",
        "lgbtq",
        "lgbtqia",
        "trans",
        "transgender",
        "gay",
        "lesbian",
        "bisexual",
        "nonbinary",
        "gender",
        "sexuality",
        "disability",
        "disabled",
        "accessibility",
        "ableism",
        "neurodivergent",
        "autism",
        "working class",
        "classism",
        "intersectional feminism",
        "womanism",
        "black feminism",
        "diaspora",
        "multicultural",
        "immigrant",
        "refugee",
        "immigration",
    ],
    "social-justice": [
        "social justice",
        "racial justice",
        "economic justice",
        "environmental justice",
        "climate justice",
        "reproductive justice",
        "equity",
        "equality",
        "diversity",
        "inclusion",
        "representation",
        "systemic racism",
        "structural inequality",
        "oppression",
        "privilege",
        "anti-racism",
        "decolonization",
        "social issues",
        "activism",
        "activist",
        "advocacy",
        "advocate",
        "human rights",
        "civil rights",
        "feminism",
        "feminist",
        "justice",
    ],
    "arts": [
        "art",
        "arts",
        "visual art",
        "photography",
        "graphic design",
        "illustration",
        "aesthetic",
        "gallery",
        "exhibition",
        "painter",
        "sculptor",
        "contemporary art",
        "fine art",
        "art exhibition",
        "art gallery",
        "visual artist",
    ],
    "media": [
        "media",
        "film",
        "movies",
        "television",
        "tv",
        "streaming",
        "podcast",
        "video",
        "entertainment",
        "cinema",
        "netflix",
        "hbo",
        "show",
        "series",
        "documentary",
        "review",
        "critic",
    ],
    "music": [
        "music",
        "musician",
        "album",
        "concert",
        "song",
        "band",
        "musical artist",
        "recording artist",
        "performing artist",
        "singer",
        "vocalist",
        "songwriter",
        "frontman",
        "lead singer",
        "rock",
        "punk",
        "indie",
        "pop",
        "hip hop",
        "rap",
        "metal",
        "electronic",
        "jazz",
        "classical",
        "pinkshift",
        "hardcore",
        "emo",
        "music industry",
        "record label",
        "afi",
        "blaqk audio",
        "davey havok",
    ],
    "books": [
        "book",
        "books",
        "literature",
        "reading",
        "novel",
        "publisher",
        "library",
        "bibliography",
    ],

    # Health & Wellness
    "health": [
        "health",
        "healthcare",
        "medical",
        "medicine",
        "doctor",
        "patient",
        "disease",
        "treatment",
        "diagnosis",
        "clinical",
        "reproductive",
        "abortion",
        "pregnancy",
        "maternal",
        "women's health",
        "bodily autonomy",
        "healthcare access",
    ],
    "wellness": [
        "wellness",
        "wellbeing",
        "fitness",
        "exercise",
        "workout",
        "nutrition",
        "diet",
        "healthy living",
        "wellness coaching",
    ],
    "mental-health": [
        "mental health",
        "psychology",
        "therapy",
        "counseling",
        "mindfulness",
        "meditation",
        "anxiety",
        "depression",
        "self-care",
        "emotional",
    ],

    # Science & Education
    "science": [
        "science",
        "scientific",
        "research",
        "study",
        "experiment",
        "discovery",
        "scientist",
        "laboratory",
        "peer review",
    ],
    "climate": [
        "climate",
        "climate change",
        "environment",
        "environmental",
        "sustainability",
        "renewable",
        "carbon",
        "emissions",
        "green energy",
        "conservation",
    ],
    "space": [
        "space",
        "astronomy",
        "astrophysics",
        "nasa",
        "rocket",
        "satellite",
        "cosmos",
        "universe",
        "planet",
        "mars",
    ],
    "education": [
        "education",
        "teaching",
        "school",
        "university",
        "college",
        "student",
        "curriculum",
        "pedagogy",
        "academic",
        "classroom",
        "teacher",
        "professor",
        "educational",
    ],

    # Career & Development
    "career": [
        "career",
        "job",
        "work",
        "employment",
        "professional",
        "workplace",
        "remote work",
        "job search",
        "interview",
        "resume",
        "career development",
        "career growth",
        "professional development",
        "working",
        "team management",
        "manager",
        "managing people",
        "1-on-1",
        "one on one",
        "feedback",
        "performance review",
    ],
    "productivity": [
        "productivity",
        "productive",
        "efficiency",
        "time management",
        "workflow",
        "organization",
        "focus",
        "habits",
        "systems",
    ],
    "personal-development": [
        "personal development",
        "self improvement",
        "growth mindset",
        "self-help",
        "motivation",
        "goals",
        "success",
        "achievement",
        "life coaching",
        "personal growth",
    ],

    # Lifestyle & Hobbies
    "food": [
        "food",
        "cooking",
        "recipe",
        "chef",
        "restaurant",
        "cuisine",
        "culinary",
        "dining",
        "foodie",
    ],
    "travel": [
        "travel",
        "traveling",
        "tourism",
        "destination",
        "adventure",
        "explore",
        "journey",
        "vacation",
        "trip",
    ],
    "sports": [
        "sports",
        "athlete",
        "game",
        "championship",
        "team",
        "player",
        "competition",
        "league",
        "tournament",
    ],
    "gaming": [
        "gaming",
        "video games",
        "gamer",
        "esports",
        "game design",
        "indie game",
        "console",
        "pc gaming",
    ],

    # Philosophy & Ideas
    "philosophy": [
        "philosophy",
        "philosophical",
        "ethics",
        "morality",
        "existential",
        "metaphysics",
        "logic",
        "epistemology",
    ],
    "history": [
        "history",
        "historical",
        "historian",
        "archive",
        "past",
        "heritage",
        "civilization",
        "ancient",
        "modern history",
    ],
    "religion": [
        "religion",
        "religious",
        "spirituality",
        "faith",
        "theology",
        "church",
        "belief",
        "sacred",
        "christian",
        "christianity",
        "catholic",
        "protestant",
        "muslim",
        "islam",
        "jewish",
        "judaism",
        "buddhist",
        "buddhism",
        "hindu",
        "hinduism",
        "atheist",
        "atheism",
        "secular",
        "pastor",
        "priest",
        "father",
        "minister",
        "rabbi",
        "imam",
    ],
    "law": [
        "law",
        "legal",
        "lawyer",
        "attorney",
        "court",
        "justice",
        "judge",
        "litigation",
        "lawsuit",
        "trial",
        "prosecutor",
        "defense",
        "constitutional",
        "supreme court",
        "legal analysis",
        "jurisprudence",
        "advocate",
        "advocacy",
    ],
}
