# definitions.py

import os
from pathlib import Path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv

    # Load .env from the script's directory
    env_path = Path(__file__).parent / ".env"
    load_dotenv(dotenv_path=env_path)
except ImportError:
    # dotenv not installed, rely on system environment variables
    pass


# HTTP headers for web scraping
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Cookie": os.getenv("SUBSTACK_COOKIE", ""),  # Load from environment variable
}

NOTION_TOKEN = os.getenv("NOTION_TOKEN")
DATABASE_ID = os.getenv("NOTION_DATABASE_ID")

# Target URL - dynamically generated from SUBSTACK_USER
SUBSTACK_USER = os.getenv("SUBSTACK_USER", "")
if SUBSTACK_USER:
    # Ensure username starts with @
    if not SUBSTACK_USER.startswith("@"):
        SUBSTACK_USER = f"@{SUBSTACK_USER}"
    SUBSTACK_URL = f"https://substack.com/{SUBSTACK_USER}/reads"
else:
    # Fallback if SUBSTACK_USER not set
    SUBSTACK_URL = ""

# Keyword categories for auto-labeling
KEYWORD_CATEGORIES = {
    # Technology & Software
    "tech": [
        "technology",
        "tech",
        "software",
        "hardware",
        "coding",
        "programming",
        "developer",
        "engineering",
        "devops",
        "cybersecurity",
        "web development",
        "mobile app",
        "open source",
    ],
    "ai": [
        "ai",
        "artificial intelligence",
        "machine learning",
        "ml",
        "deep learning",
        "neural network",
        "llm",
        "gpt",
        "chatbot",
        "nlp",
        "computer vision",
        "generative ai",
    ],
    "crypto": [
        "crypto",
        "cryptocurrency",
        "bitcoin",
        "ethereum",
        "blockchain",
        "web3",
        "defi",
        "nft",
        "smart contract",
        "decentralized",
    ],
    "startups": [
        "startup",
        "startups",
        "founder",
        "venture capital",
        "vc",
        "saas",
        "entrepreneur",
        "fundraising",
        "product market fit",
        "mvp",
        "growth hacking",
    ],

    # Business & Finance
    "business": [
        "business",
        "commerce",
        "industry",
        "corporate",
        "company",
        "management",
        "leadership",
        "strategy",
        "operations",
        "consulting",
    ],
    "finance": [
        "finance",
        "investing",
        "stocks",
        "trading",
        "markets",
        "economy",
        "economics",
        "money",
        "wealth",
        "personal finance",
        "portfolio",
        "asset",
    ],
    "marketing": [
        "marketing",
        "growth",
        "branding",
        "advertising",
        "seo",
        "content marketing",
        "social media",
        "analytics",
        "conversion",
        "customer acquisition",
    ],

    # News & Politics
    "news": [
        "news",
        "journalism",
        "reporter",
        "correspondent",
        "breaking news",
        "current events",
        "headlines",
        "newsroom",
        "investigative",
        "reporting",
    ],
    "politics": [
        "politics",
        "political",
        "policy",
        "government",
        "congress",
        "senate",
        "legislation",
        "election",
        "democracy",
        "governance",
        "public policy",
        "activist",
        "activism",
        "progressive",
        "conservative",
        "liberal",
        "rights",
        "civil rights",
        "human rights",
        "equality",
        "justice",
        "protest",
        "resistance",
        "reform",
        "congressman",
        "congresswoman",
        "representative",
        "senator",
    ],
    "world": [
        "international",
        "global",
        "geopolitics",
        "foreign policy",
        "diplomacy",
        "world affairs",
        "conflict",
        "war",
        "peace",
    ],

    # Creative & Culture
    "writing": [
        "writing",
        "writer",
        "author",
        "storytelling",
        "creative writing",
        "fiction",
        "poetry",
        "prose",
        "essays",
        "memoir",
    ],
    "culture": [
        "culture",
        "cultural",
        "society",
        "trends",
        "pop culture",
        "zeitgeist",
        "social commentary",
        "identity",
        "community",
        "queer",
        "lgbtq",
        "lgbtqia",
        "trans",
        "transgender",
        "gay",
        "lesbian",
        "bisexual",
        "nonbinary",
        "gender",
        "sexuality",
        "diversity",
        "inclusion",
        "representation",
        "marginalized",
        "minority",
    ],
    "arts": [
        "art",
        "arts",
        "visual art",
        "photography",
        "design",
        "illustration",
        "creative",
        "aesthetic",
        "gallery",
        "exhibition",
    ],
    "media": [
        "media",
        "film",
        "movies",
        "television",
        "tv",
        "streaming",
        "podcast",
        "video",
        "entertainment",
        "cinema",
    ],
    "music": [
        "music",
        "musician",
        "album",
        "concert",
        "song",
        "band",
        "artist",
        "audio",
        "sound",
        "singer",
        "vocalist",
        "rock",
        "punk",
        "indie",
        "pop",
        "hip hop",
        "rap",
        "metal",
        "electronic",
        "jazz",
        "classical",
    ],
    "books": [
        "book",
        "books",
        "literature",
        "reading",
        "novel",
        "publisher",
        "library",
        "bibliography",
    ],

    # Health & Wellness
    "health": [
        "health",
        "healthcare",
        "medical",
        "medicine",
        "doctor",
        "patient",
        "disease",
        "treatment",
        "diagnosis",
        "clinical",
        "reproductive",
        "abortion",
        "pregnancy",
        "maternal",
        "women's health",
        "bodily autonomy",
        "healthcare access",
    ],
    "wellness": [
        "wellness",
        "wellbeing",
        "fitness",
        "exercise",
        "workout",
        "nutrition",
        "diet",
        "healthy",
        "lifestyle",
    ],
    "mental-health": [
        "mental health",
        "psychology",
        "therapy",
        "counseling",
        "mindfulness",
        "meditation",
        "anxiety",
        "depression",
        "self-care",
        "emotional",
    ],

    # Science & Education
    "science": [
        "science",
        "scientific",
        "research",
        "study",
        "experiment",
        "discovery",
        "scientist",
        "laboratory",
        "peer review",
    ],
    "climate": [
        "climate",
        "climate change",
        "environment",
        "environmental",
        "sustainability",
        "renewable",
        "carbon",
        "emissions",
        "green energy",
        "conservation",
    ],
    "space": [
        "space",
        "astronomy",
        "astrophysics",
        "nasa",
        "rocket",
        "satellite",
        "cosmos",
        "universe",
        "planet",
        "mars",
    ],
    "education": [
        "education",
        "learning",
        "teaching",
        "school",
        "university",
        "college",
        "student",
        "curriculum",
        "pedagogy",
        "academic",
    ],

    # Career & Development
    "career": [
        "career",
        "job",
        "work",
        "employment",
        "professional",
        "workplace",
        "remote work",
        "job search",
        "interview",
        "resume",
    ],
    "productivity": [
        "productivity",
        "productive",
        "efficiency",
        "time management",
        "workflow",
        "organization",
        "focus",
        "habits",
        "systems",
    ],
    "personal-development": [
        "personal development",
        "self improvement",
        "growth mindset",
        "learning",
        "skills",
        "motivation",
        "goals",
        "success",
        "achievement",
    ],

    # Lifestyle & Hobbies
    "food": [
        "food",
        "cooking",
        "recipe",
        "chef",
        "restaurant",
        "cuisine",
        "culinary",
        "dining",
        "foodie",
    ],
    "travel": [
        "travel",
        "traveling",
        "tourism",
        "destination",
        "adventure",
        "explore",
        "journey",
        "vacation",
        "trip",
    ],
    "sports": [
        "sports",
        "athlete",
        "game",
        "championship",
        "team",
        "player",
        "competition",
        "league",
        "tournament",
    ],
    "gaming": [
        "gaming",
        "video games",
        "gamer",
        "esports",
        "game design",
        "indie game",
        "console",
        "pc gaming",
    ],

    # Philosophy & Ideas
    "philosophy": [
        "philosophy",
        "philosophical",
        "ethics",
        "morality",
        "existential",
        "metaphysics",
        "logic",
        "epistemology",
    ],
    "history": [
        "history",
        "historical",
        "historian",
        "archive",
        "past",
        "heritage",
        "civilization",
        "ancient",
        "modern history",
    ],
    "religion": [
        "religion",
        "religious",
        "spirituality",
        "faith",
        "theology",
        "church",
        "belief",
        "sacred",
        "christian",
        "christianity",
        "catholic",
        "protestant",
        "muslim",
        "islam",
        "jewish",
        "judaism",
        "buddhist",
        "buddhism",
        "hindu",
        "hinduism",
        "atheist",
        "atheism",
        "secular",
        "pastor",
        "priest",
        "father",
        "minister",
        "rabbi",
        "imam",
    ],
    "law": [
        "law",
        "legal",
        "lawyer",
        "attorney",
        "court",
        "justice",
        "judge",
        "litigation",
        "lawsuit",
        "trial",
        "prosecutor",
        "defense",
        "constitutional",
        "supreme court",
        "legal analysis",
        "jurisprudence",
        "advocate",
        "advocacy",
    ],
}

# Known authors database for better categorization
# Maps author names to their primary topics/background
KNOWN_AUTHORS = {
    "davey havok": ["music", "punk", "rock", "afi", "band"],
    "davey": ["music", "punk", "rock"],
    "margaret atwood": ["writing", "books", "literature", "fiction", "author"],
    "heather cox richardson": ["history", "politics", "historian"],
    "ruth ben-ghiat": ["history", "politics", "authoritarianism"],
    "chase strangio": ["law", "lgbtq", "trans", "civil rights", "aclu"],
    "jessica valenti": ["feminism", "reproductive rights", "abortion", "politics"],
    "eliza orlins": ["law", "criminal justice", "public defender"],
}
